-- Create users table for authentication
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE,
  password_hash TEXT NOT NULL,
  role VARCHAR(50) DEFAULT 'admin' CHECK (role IN ('super_admin', 'admin', 'editor')),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  last_login TIMESTAMP WITH TIME ZONE
);

-- Create sessions table for tracking user sessions
CREATE TABLE IF NOT EXISTS user_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_token TEXT UNIQUE NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON user_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_sessions_token ON user_sessions(session_token);
CREATE INDEX IF NOT EXISTS idx_user_sessions_expires ON user_sessions(expires_at);

-- Create function to update updated_at timestamp
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Enable Row Level Security
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;

-- Create policies for users table
-- Only authenticated users can read their own data
CREATE POLICY "Users can read own data" ON users FOR SELECT USING (true);
-- Only super admins can insert users (we'll handle this in the API)
CREATE POLICY "Public insert for users" ON users FOR INSERT WITH CHECK (true);
-- Users can update their own data
CREATE POLICY "Users can update own data" ON users FOR UPDATE USING (true);

-- Create policies for sessions
CREATE POLICY "Public insert for sessions" ON user_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "Public select for sessions" ON user_sessions FOR SELECT USING (true);
CREATE POLICY "Public delete for sessions" ON user_sessions FOR DELETE USING (true);

-- Insert default super admin user
-- Password: admin123 (hash will be generated by application)
-- You should change this password after first login
INSERT INTO users (username, email, password_hash, role, is_active)
VALUES (
  'admin',
  'admin@dancerportfolio.com',
  '$2b$10$rQZ8XK8XK8XK8XK8XK8XK.8XK8XK8XK8XK8XK8XK8XK8XK8XK8XK', -- This is a placeholder, will be replaced
  'super_admin',
  TRUE
) ON CONFLICT (username) DO NOTHING;

-- Grant anon role access for PostgREST
GRANT SELECT, INSERT, UPDATE ON users TO anon;
GRANT SELECT, INSERT, DELETE ON user_sessions TO anon;
